local builtin = require('telescope.builtin')

vim.keymap.set('n', '<leader>fg', builtin.git_files, {})
vim.keymap.set('n', '<C-g>', builtin.git_files, {})
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>sg', builtin.live_grep, {})
vim.keymap.set('n', '<leader>fb', builtin.buffers, {})
vim.keymap.set('n', '<leader>gr', builtin.git_branches, {})
vim.keymap.set('n', '<leader>gb', function()
    builtin.git_branches({ show_remote_tracking_branches = false })
end, {})
vim.keymap.set('n', '<leader>gs', builtin.git_stash, {})
vim.keymap.set('n', '<leader>wd', builtin.diagnostics, {})